name: Update README

on:
    schedule:
        - cron: "*/5760 * * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Recent GitHub Activity - Profile Readme

		settings:
			disabled_events: []

        steps:
            - uses: actions/checkout@v2.3.4
            - uses: Readme-Workflows/recent-activity@v2.3.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
